name = "AlgebraOfGraphics"
uuid = "cbdf2221-f076-402e-a563-3d30da359d67"
authors = ["Pietro Vertechi"]
version = "0.6.11"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
GridLayoutBase = "3955a311-db13-416c-9275-1d80ed98e5e9"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
RelocatableFolders = "05181044-ff0b-4ac5-8273-598c1e38db00"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Colors = "0.12"
Dictionaries = "0.3"
FileIO = "1.1"
GLM = "1.7"
GeoInterface = "1"
GeometryBasics = "0.4.1"
GridLayoutBase = "0.6, 0.7, 0.8, 0.9"
KernelDensity = "0.6"
Loess = "0.5.1"
Makie = "0.17.6, 0.18"
PlotUtils = "1"
PooledArrays = "1"
RelocatableFolders = "0.1, 0.2, 0.3, 1.0"
StatsBase = "0.33"
StructArrays = "0.5, 0.6"
Tables = "1.4"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Shapefile = "8e980c4a-a4fe-5da2-b3a7-4b4b0353a2f4"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Shapefile", "Statistics", "Test"]
