name = "AlgebraOfGraphics"
uuid = "cbdf2221-f076-402e-a563-3d30da359d67"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.1.0"

[deps]
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
DataAPI = "1"
Observables = "0.2, 0.3"
PooledArrays = "0.5"
Requires = "1"
StructArrays = "0.4.3"
Tables = "1"
julia = "1"

[extras]
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["RDatasets", "Test"]
