name = "AlgebraOfGraphics"
uuid = "cbdf2221-f076-402e-a563-3d30da359d67"
authors = ["Pietro Vertechi <pietro.vertechi@veos.digital>"]
version = "0.4.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataAPI = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
GridLayoutBase = "3955a311-db13-416c-9275-1d80ed98e5e9"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AbstractPlotting = "0.15, 0.16, 0.17, 0.18"
Colors = "0.12"
DataAPI = "1"
FileIO = "1.1"
GLM = "1.4"
GridLayoutBase = "0.5"
KernelDensity = "0.6"
Loess = "0.5"
OrderedCollections = "1"
PlotUtils = "1.0"
PooledArrays = "1"
StatsBase = "0.33"
StructArrays = "0.5"
Tables = "1.4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]