name = "AlgebraOfGraphics"
uuid = "cbdf2221-f076-402e-a563-3d30da359d67"
authors = ["Pietro Vertechi <pietro.vertechi@neuro.fchampalimaud.org>"]
version = "0.1.0"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
GLM = "38e38edf-8417-5370-95a0-9cbb8c7f171a"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
NamedDims = "356022a1-0364-5f58-8944-0da4b18d706f"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
AbstractPlotting = "0.12"
CategoricalArrays = "0.8"
GLM = "1"
KernelDensity = "0.5"
Loess = "0.5"
NamedDims = "0.2"
Observables = "0.3"
StatsBase = "0.31, 0.32, 0.33"
StructArrays = "0.4.3"
Tables = "1"
julia = "1"

[extras]
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["RDatasets", "Test"]
